import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import { signIn } from 'next-auth/react'

function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <div className="grid place-items-center">
        <Image
          src="https://links.papareact.com/t4i"
          width={400}
          height={400}
          objectFit="contain"
          alt=""
        />
        <h1 onClick={() => signIn()} className="text-white font-bold text-xl p-5 bg-blue-500 rounded-full outline-none cursor-pointer ease-in duration-200 hover:bg-blue-600">
          Log in with Facebook
        </h1>
      </div>
    </>
  )
}

export default Login
