import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

function Login() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <Image
        src="https://links.papareact.com/t4i"
        width={400}
        height={400}
        objectFit="contain"
        alt=""
      />
    </div>
  )
}

export default Login
