import Head from 'next/head'
import Header from '../components/Header/Header'

import { useSession } from 'next-auth/react'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar/Sidebar'
import Feed from '../components/Feed/Feed'

export default function Home() {
  const { data: session } = useSession()
  if (!session) return <Login />

  return (
    <>
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <div>
        <Header />
        <main className="flex">
          <Sidebar />
          <Feed />
        </main>
      </div>
    </>
  )
}
